# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: action-maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: comchangs/action-maven@v0.4-beta
    - name: Set up JDK 11
      uses: comchangs/action-maven@v0.4-beta
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with maven
      run: mvn clean package 
